# app/routes/predict.py
from fastapi import APIRouter, HTTPException, status
from app.models import StudentFeatures, PredictionResponse, RiskCategory, Intervention

router = APIRouter()

# Temporary placeholder function (will be replaced with real ML model in Week 2)
def get_mock_prediction(features: StudentFeatures) -> PredictionResponse:
    """Mock prediction for testing the API before ML model is ready"""
    
    # "The current scoring function is a mock heuristic for API testing. 
    # In production, the score would either be generated by a trained machine-learning model 
    # or by a normalized weighted scoring system whose maximum and minimum values are explicitly defined."
    # difference between a placeholder rule-based system and a properly calibrated predictive model 
    # is that the latter would be trained on historical data to learn the optimal weights and interactions between features, 
    # and would be calibrated to produce risk scores that accurately reflect the true probabilities of dropout. 
    # The mock function, on the other hand, uses arbitrary weights and a simple formula that may not capture the complex relationships between features or produce well-calibrated risk scores.
    # Simple mock logic: lower attendance = higher risk
    risk_score = max(0, min(100, 
        # 50 +  # base risk
        (100 - features.attendance_rate) * 0.5 +
        (100 - features.assignments_completed) * 0.3 +
        features.days_absent_last_term * 1.5 +
        features.disciplinary_incidents * 5
    ))
    
    # Determine risk category
    if risk_score < 40:
        category = RiskCategory.LOW
    elif risk_score < 70:
        category = RiskCategory.MEDIUM
    else:
        category = RiskCategory.HIGH
    
    # Generate mock factors
    top_factors = [
        {"feature": "attendance_rate", "value": features.attendance_rate, "impact": f"+{(100 - features.attendance_rate) * 0.5:.1f}"},
        {"feature": "assignments_completed", "value": features.assignments_completed, "impact": f"+{(100 - features.assignments_completed) * 0.3:.1f}"},
        {"feature": "days_absent_last_term", "value": features.days_absent_last_term, "impact": f"+{features.days_absent_last_term * 1.5:.1f}"}
    ]
    
    # Generate mock interventions
    interventions = []
    if features.attendance_rate < 80:
        interventions.append(Intervention(
            action="Schedule parent-teacher meeting",
            priority="High",
            reason=f"Attendance rate is {features.attendance_rate}% (below 80% threshold)"
        ))
    if features.assignments_completed < 75:
        interventions.append(Intervention(
            action="Provide homework support group",
            priority="Medium",
            reason=f"Only {features.assignments_completed}% of assignments completed"
        ))
    if features.days_absent_last_term > 10:
        interventions.append(Intervention(
            action="Contact family for attendance support",
            priority="High",
            reason=f"{features.days_absent_last_term} absences in last term"
        ))
    if features.disciplinary_incidents > 0:
        interventions.append(Intervention(
            action="Schedule counseling session",
            priority="Medium",
            reason=f"{features.disciplinary_incidents} disciplinary incident(s) reported"
        ))
    
    if not interventions:
        interventions.append(Intervention(
            action="Continue current support",
            priority="Low",
            reason="No immediate risk factors detected"
        ))
    
    return PredictionResponse(
        risk_score=round(risk_score, 1),
        risk_category=category,
        top_factors=top_factors,
        interventions=interventions
    )

@router.post("/predict", response_model=PredictionResponse, status_code=status.HTTP_200_OK)
async def predict_dropout_risk(student: StudentFeatures):
    """
    Predict student dropout risk based on academic, behavioral, and demographic features.
    
    Returns:
    - risk_score: 0-100 score indicating dropout probability
    - risk_category: Low, Medium, or High
    - top_factors: Top 3 factors contributing to the risk score
    - interventions: Recommended actions to reduce risk
    """
    try:
        # Week 1: Using mock prediction
        # Week 2: Replace with real ML model
        result = get_mock_prediction(student)
        return result
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Prediction failed: {str(e)}"
        )

@router.get("/health")
async def route_health():
    return {"route": "predict", "status": "healthy"}